# Code Generated by ZenTest v. 4.1.4
#                 classname: asrt / meth =  ratio%
#                 FtpChange:    0 /   10 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

class TestFtpChange < Test::Unit::TestCase
  def test_class_change
    raise NotImplementedError, 'Need to write test_class_change'
  end

  def test_class_delete
    raise NotImplementedError, 'Need to write test_class_delete'
  end

  def test_action
    raise NotImplementedError, 'Need to write test_action'
  end

  def test_base_pathnames
    raise NotImplementedError, 'Need to write test_base_pathnames'
  end

  def test_directory_action
    raise NotImplementedError, 'Need to write test_directory_action'
  end

  def test_execute_via
    raise NotImplementedError, 'Need to write test_execute_via'
  end

  def test_file_action
    raise NotImplementedError, 'Need to write test_file_action'
  end

  def test_local_path
    raise NotImplementedError, 'Need to write test_local_path'
  end

  def test_remote_path
    raise NotImplementedError, 'Need to write test_remote_path'
  end
end

# Number of errors detected: 10
