# Code Generated by ZenTest v. 4.1.4
#                 classname: asrt / meth =  ratio%
#                  SCM::Svn:    0 /    2 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

module TestSCM
  class TestSvn < Test::Unit::TestCase
    def test_binary
      raise NotImplementedError, 'Need to write test_binary'
    end

    def test_find_version
      raise NotImplementedError, 'Need to write test_find_version'
    end

    def test_revision
      raise NotImplementedError, 'Need to write test_revision'
    end
  end
end

# Number of errors detected: 5
